### ISSUE TITLE
☂️ Japanese Translation Progress (Contributing)

### ISSUE THREAD

**Issue by Naturalclar** [gatsbyjs/gatsby-ja#196]
# Contributing下のファイルの翻訳 Issue です。

## 翻訳者へ

ページを翻訳するために:

1. あなたが翻訳したいページについて、以下のチェックリストとコメント欄を見て、他の誰も翻訳することを宣言していないことを確認してください。
2. この Issue に、翻訳したいページ名をコメントしてください。**1 ページづつでお願いします**。
3. `gatsby-ja`リポジトリを Clone して、該当するページを翻訳しましょう！
   1. 困ったら[翻訳スタイルガイド](https://github.com/gatsbyjs/gatsby-ja/blob/master/style-guide.md)に目を通してください。
   1. 翻訳した文章を音読してみましょう。明らかに不自然な表現を見つけやすくなります。
   1. 表現で迷ったら Discord で相談してみましょう！
4. 翻訳と校正を終えたら、Pull Request を送りましょう！
   1. `Allow edits from maintainer`にチェックを入れるのを忘れずに。
   2. しばらく待ってもレビューが終わらなかったり、必要なレビュー数が足りない状態が続いた場合は、メンテナーの誰かに@を付けてメンションを飛ばしてください。

貢献する前に、[Translation Guide](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#contributing-to-a-translation)を一読して、Gatsby の翻訳プロセスへの理解を深めてください。また、[翻訳スタイルガイド](https://github.com/gatsbyjs/gatsby-ja/blob/master/style-guide.md)にも目を通してください。

**自分で宣言したページは早めに翻訳してください！**：もし、時間の都合が取れなくなったり、進めなくなったりしたら、他の人に振れるようにするために、メンテナーの誰かにお知らせください。

その他わからないことがあれば、[Gatsby Discord](https://gatsby.dev/discord) の `#translation-ja` チャンネルで質問してください！

### メンテナー

- @Naturalclar
- @hirotaka
- @uetchy
- @imbsky

## 翻訳済みページ

- [x] #206  contributing/how-to-open-a-pull-request (@HelloTakako) 
- [x] #127 contributing/community-contributions (@yukisato)
- [x] #133 contributing/community (@yukisato)
- [x] #18 contributing/why-contribute-to-gatsby (@sanposhiho)
- [x] #173 contributing/contributor-swag (@taka-take) 2020-02-10
- [x] #211 contributing/gatsby-docs-translation-guide (@yicru)
- [x] #199  contributing/how-to-contribute (@toshi-toma)
- [x] #197  contributing/how-to-file-an-issue (@kawamataryo)
- [x] #198  contributing/how-to-label-an-issue (@saitoeku3)
- [x] #210 contributing/stub-list (@96-38)
- [x] #206 contributing/how-to-open-a-pull-request (@HelloTakako)
- [x] #239 contributing/submit-to-plugin-library (@saitoeku3)
- [x] #238 contributing/setting-up-your-local-dev-environment (@mottox2)

## 翻訳中のページ

- [ ] 🏃 contributing/blog-and-website-contributions (@moksahero) 2020-01-25
- [ ] 🏃 contributing/code-contributions (@codyNog) 2020-01-26
- [ ] contributing/where-to-participate (@konekato)
- [ ] 🏃 contributing/setting-up-your-local-dev-environment (@mottox2)
- [ ] 🏃‍♀️ contributing/submit-to-starter-library (@akthrms)
- [ ] 🏃 contributing/index (@shirarin)

## 未翻訳ページ

- [ ] contributing/code-of-conduct
- [ ] contributing/docs-and-website-components
- [ ] contributing/docs-contributions
- [ ] contributing/docs-templates
- [ ] contributing/gatsby-governance-model
- [ ] contributing/gatsby-style-guide
- [ ] contributing/how-to-make-a-reproducible-test-case
- [ ] contributing/how-to-pitch-gatsby
- [ ] contributing/how-to-run-a-gatsby-workshop
- [ ] contributing/how-to-write-a-stub
- [ ] contributing/managing-pull-requests
- [ ] contributing/organize-a-gatsby-event
- [ ] contributing/pair-programming
- [ ] contributing/rfc-process
- [ ] contributing/site-showcase-submissions
- [ ] contributing/submit-to-creator-showcase
- [ ] contributing/triaging-github-issues/index
- [ ] contributing/using-an-online-dev-environment
- [ ] contributing/how-to-file-an-issue

**Comment by kawamataryo** [comment]
I'd like to translate `contributing/how-to-file-an-issue`

**Comment by Naturalclar** [comment]
@kawamataryo Go for it :+1:

**Comment by toshi-toma** [comment]
I'd like to translate contributing/how-to-contribute

**Comment by Naturalclar** [comment]
@toshi-toma Go for it 🚀

**Comment by saitoeku3** [comment]
I'd like to translate `contributing/how-to-label-an-issue`.

**Comment by Naturalclar** [comment]
@saitoeku3 Go for it :tada:

**Comment by shirarin** [comment]
I'd like to translate `contributing/index`.

**Comment by saitoeku3** [comment]
I'd like to translate `contributing/submit-to-plugin-library`

**Comment by 96-38** [comment]
I'd like to translate `contributing/stub-list`

**Comment by yicru** [comment]
I'd like to translate `contributing/gatsby-docs-translation-guide `

**Comment by mottox2** [comment]
I'd like to translate `contributing/setting-up-your-local-dev-environment`

**Comment by akthrms** [comment]
I'd like to translate `contributing/submit-to-starter-library`

**Comment by konekato** [comment]
I'll translate `contributing/where-to-participate`.

**Comment by takakd** [comment]
I'd like to try to translate `using-an-online-dev-environment`.

**Comment by AnguillaJaponica** [comment]
I'll translate  `contributing/gatsby-governance-model`

**Comment by PasinduDushan** [comment]
I'll translate `contributing/how-to-pitch-gatsby`
